name: trucku_borneo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  http: ^0.13.5
  cached_network_image: ^3.2.3
  get: ^4.6.5
  flutter_svg: ^1.1.6
  get_storage: ^2.0.3
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  flutter_launcher_icons: ^0.11.0
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_geocoder: ^0.2.2-nullsafety
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.5.0
  intl: ^0.18.0
  duration: ^3.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
